### ISSUE TITLE
Request for beta access

### ISSUE THREAD

**Issue by JamesDFloyd** [shakee93/autoptimize-unusedcss#25]
I manage a variety of WordPress sites for small businesses, and I am very excited to help you test and perfect your autoptimize-unusedcss plugin!

**Comment by shakee93** [comment]
Hey James, drop your email address please, ill send you over the access details.

Thanks.

**Comment by JamesDFloyd** [comment]
Hello Shakeeb!

Thank you very much! My email address is james_d_floyd1@msn.com<mailto:james_d_floyd1@msn.com>

I’m very excited to join the beta for your very interesting plugin!

Thanks again,

James

**Comment by shakee93** [comment]
Thank you James, dropped you a mail with the details. 

looking forward to hearing from you.
