### ISSUE TITLE
Beta Access Please

### ISSUE THREAD

**Issue by heartlandbr** [shakee93/autoptimize-unusedcss#27]
I would like to beta your plugin. It would be on a development woocommerce site.

**Comment by shakee93** [comment]
Drop your email address please.

Thanks.

**Comment by heartlandbr** [comment]
See below

Thank you,

Brian R. Greene, Owner
Heartland Braided Rugs, Inc
brian@heartlandbraidedrugs.com<mailto:brian@heartlandbraidedrugs.com>
customerservice@heartlandbraidedrugs.com<mailto:customerservice@heartlandbraidedrugs.com>
