### ISSUE TITLE
I would like to get BETA access

### ISSUE THREAD

**Issue by mrgarry043** [shakee93/autoptimize-unusedcss#29]
Hi there, I always have trouble with unused CSS and many times attempted to remove it manually which is almost an impossible task.

Just saw someone shared this within the Facebook group and am excited to be part to beta testers, I work for an agency and can test on all kind of websites such as LMS, Membership, WooCommerce and so on.

**Comment by shakee93** [comment]
Hey Garry, drop your email address please. will send you the access information

Thanks.
