### ISSUE TITLE
I want be a beta tester

### ISSUE THREAD

**Issue by jbco00** [shakee93/autoptimize-unusedcss#30]
Hi, looking foward to be a beta tester, thank you

**Comment by shakee93** [comment]
Drop your email address please,

Thanks.

**Comment by jbco00** [comment]
Hi Shakeeb,

jbco00pop@gmail.com

Thank you



Em seg., 24 de ago. de 2020 às 02:42, Shakeeb Sadikeen <
notifications@github.com> escreveu:

**Comment by shakee93** [comment]
Hey sent you the access details, looking forward to your feedback.

Thanks
