### ISSUE TITLE
Powerup plugin does not yet use 'autoptimize_filter_cache_create_static_gzip'

### ISSUE THREAD

**Issue by utrenkner** [shakee93/autoptimize-unusedcss#38]
Autoptimize offers a filter to enable pre-compression for the generated CSS and JS files. All cached files are then also available as .gz - and if PHP's brotli extension is available - also as .br. In order to make use of this feature, one just has to add this code:
``add_filter('autoptimize_filter_cache_create_static_gzip','__return_true');``
Or else install the [autoptimize gzip plugin](https://github.com/centminmod/autoptimize-gzip) which adds this this line of code.

The CSS file created by autoptimize-unusedcss powerup does not yet implement this filter. And as I have on-the-fly compression disabled, the file is currently transmitted without any compression. It would be great, if this powerup was able to pre-compress CSS files, too.

Many thanks.

**Comment by shakee93** [comment]
it needs quiet a bit more workaround to save files of unusedCSS. ill look into this and see how is the possibility

**Comment by utrenkner** [comment]
Thank you!!!
