### ISSUE TITLE
Unclear or misleading wording of options

### ISSUE THREAD

**Issue by utrenkner** [shakee93/autoptimize-unusedcss#41]
This is a non-technical issue.

The wording of the minify option is unclear to me: ``Disable Minify -- minify and remove css comments via the api``. When the option is clicked, does it mean minification is disabled or enabled?

Similarly, I am not 100% sure about the others: E.g. does ``Disable Variables -- remove unused css variables`` mean that I disable the function to remove unused css variables? Or does it actually enable this function. If the latter, maybe "Remove variables" would be a better title?

FYI, I also tested new code from Master. Plugin installed, CSS files are generated, but they seem to be never linked in the pages. But you probably knew this already...

**Comment by shakee93** [comment]
Thank you @utrenkner appreciate your interest. 

`Disable Minify -- minify and remove css comments via the api` 
this means even though AO does minification UnusedCSS has its own minification after removing unusedcss. you can disable or enable this option.

`Disable Variables -- remove unused css variables`
Sometimes unusedCSS can flag CSS variables wrongly. so it is optional as well.

if you have a better naming suggestion we would love to consider adding it.

and can you send me a support access to your site ? email me though, I can take a look.

**Comment by utrenkner** [comment]
Hi @shakee93,

I think it would help, if the name of the option and the explanation were written from the some perspective. E.g. "Disable Variables -- do not remove css variables" or "Disable Minify -- do not minify or remove css comments".

Giving you access to the our test server backend would not help, because we also use caching (on the web server itself, somewhat similar to Varnish) and I would have to give you access to that cache, too. 

Anyway, today, I installed the latest code from master, and now the plugin works again. If I do not encounter any problems, I will likely try it in production, too (where 0.0.1 is working happily, already).
